### ISSUE TITLE
zsh mac jd function in .zshrc

### ISSUE THREAD

**Issue by mattburman** [cgmcintyr/jumpdir#1]
Traceback (most recent call last):
  File "/usr/local/bin/jumpdir", line 5, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/jumpdir/main.py", line 57, in main
    bm = Bookmarks(BOOKMARKS)
  File "/usr/local/lib/python2.7/site-packages/jumpdir/bookmarks.py", line 24, in __init__
    self.load_bookmarks()
  File "/usr/local/lib/python2.7/site-packages/jumpdir/bookmarks.py", line 76, in load_bookmarks
    self.bm_dict = json.loads(jfile.read())
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
jd:3: parse error: condition expected: !=
Jumpdir could not find a matching directory :(

**Comment by asfaltboy** [comment]
Same happens for me. It seems Jumpdir creates some empty cache files (at least for OSX El Capitan) and later fails to decode them as JSON. To solve this we could simply write an empty dict when we create the files (or avoid creating them at all?).

Even if I fix that manually, the "initial search" which I assume builds a dictionary of all directories in `HOME_DIR`, takes a very very long time. Maybe it would be better to build the cache incrementally when a certain depth (1-2 dirs) is reached?

**Comment by cgmcintyr** [comment]
Thanks for the PR request @asfaltboy, I've merged your changes to master. 

Jumpdir started off as a personal project, so the edges are a bit rough. I am open to the idea of incremental cache generation to reduce the overhead of the "initial search". 

At the moment on the first run of JD the 'map_directories' method is called, which creates the dictionary representing HOME_DIR through a call to the 'dict_builder' function, and then saves the dictionary to the cache file in JSON format. 

Furthermore if jumpdir cannot find a matching directory when searching, it will call 'map_directories' to rebuild the dictionary + cache in case the directory the user is searching for was created after cache generation.

**Comment by asfaltboy** [comment]
Honestly, I just tried Jumpdir today for the first time. I was actually looking for [wting/autojump](https://github.com/wting/autojump) but found your project because I could not remember the name 😊
